# Generated by Django 3.0.3 on 2020-03-22 12:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('game', models.TextField(blank=True, choices=[], null=True)),
                ('started', models.BooleanField(default=False)),
                ('state', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
