# Generated by Django 3.0.3 on 2020-03-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.TextField(blank=True, choices=[('bussen', 'bussen')], null=True),
        ),
    ]
