# Generated by Django 3.0.3 on 2020-03-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_bussen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='game',
            new_name='room',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('room', 'name')},
        ),
    ]
